apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-frontend
  namespace: yolo
  labels:
    app: yolo
    component: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      component: frontend
  template:
    metadata:
      labels:
        app: yolo
        component: frontend
    spec:
      containers:
        - name: yolo_frontend
          image: lennydennis/yolo_frontend:1
          ports:
            - containerPort: 3000
         
---
apiVersion: v1
kind: Service
metadata:
  name: yolo-frontend
  namespace: yolo
  labels:
    app: yolo
    component: frontend
spec:
  type: LoadBalancer
  selector:
    app: yolo
    component: frontend
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http