
---
- name: Yolo Playbook
  hosts: all
  become: true
  vars:
    repo: "https://github.com/LennyDennis/yolo"
    dest: "/home/lenny/yolo"
  tasks:
    - name: Install Git
      include_role:
        name: git
    
    - name: checkout git repo
      git:
        repo: "{{ repo }}"
        dest: "{{ dest }}"


    - name: Install Docker
      include_role:
        name: docker

    - name: Install image and container for the applicaton
      include_role:
        name: docker-compose